moms/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(
        'login/$',
        auth_views.LoginView.as_view(
            template_name="accounts/login.html",
        ),
        name="login",
    ),
]

moms/moms/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    # Public
    url(r'^', include('public.urls', namespace="public")),
]

moms/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class MomsUser(User):
    """
    Proxy model to enhance :model:`auth.User` model logic.
    This will be our default User model.
    """
    class Meta:
        proxy = True

    def is_manager(self):
        """
        Designate whether the user has manager permissions.
        """
        return hasattr(self, 'manager')

    def is_member(self):
        """
        Designate whether the user has member permissions.
        """
        return hasattr(self, 'member')


class Manager(models.Model):
    """
    Profile model for manager users.
    """
    user = models.OneToOneField(MomsUser, on_delete=models.CASCADE)


class Member(models.Model):
    """
    Profile model for member users.
    """
    user = models.OneToOneField(MomsUser, on_delete=models.CASCADE)

moms/private/models.py
from django.db import models

# Create your models here.

moms/accounts/views.py
from django.shortcuts import render

# Create your views here.

moms/private/views.py
from django.shortcuts import render

# Create your views here.

moms/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
  
  <div class="col-lg-10 col-md-10" style="background: #fff;">

    <div class="row">

      <div class="col-lg-6 col-md-6">
	<h3 class="page-header">Login</h3>

	{% if form.errors %}
	<div class="alert alert-danger">
	  Username or password are not correct! Please check your credentials and try again.
	</div>
	{% endif %}

	{% if next %}

	{% if user.is_authenticated %}
	<div class="alert alert-warning">
	  Your account doesn't have access to this page. To proceed, please login with an account that has access.
	</div>
	{% else %}
	<div class="alert alert-info">
	  Please login to see this page.
	</div>
	{% endif %}

	{% endif %}

	<form method="post" action="{% url 'accounts:login' %}">

	  {% csrf_token %}

	  <div class="form-group">
	    <label>{{ form.username.label_tag }}</label>
	    {{ form.username }}
	  </div>

	  <div class="form-group">
	    <label>{{ form.password.label_tag }}</label>
	    {{ form.password }}
	  </div>

	  <div class="form-group text-right">
	    <button id="login" type="submit" class="btn btn-danger">Access</button>
	  </div>
	  
	</form>
	
      </div>

      <div class="col-lg-6 col-md-6">

	    <div class="card">

	      <div class="card-block">
		
		<h1 class="card-text text-center">Welcome to <strong>M.O.M.S.</strong></h1>
		
	      </div>

	      <img class="card-image-bottom img-fluid" src="{% static 'img/moms-logo.jpg' %}">
	      
	    </div>

      </div>

    </div>

  </div>
  
</div>

{% endblock content %}

moms/private/templates/private/basic.html
{% load static %}
{% extends "base.html" %}

{% block extra_head_css %}
{% endblock extra_head_css %}

{% block navbar %}

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SB Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="charts.html"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-fw fa-table"></i> Tables</a>
                    </li>
                    <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
{% endblock navbar %}

{% block content %}
{% endblock content %}
	
{% block extra_body_js %}
{% endblock extra_body_js %}
	

moms/private/templates/private/blank_page.html
{% extends "private/basic.html" %}

{% block extra_head_css %}
{% endblock extra_head_css %}

{% block content %}
<div id="page-wrapper">

  <div class="container-fluid">

    {% block page %}
    {% endblock page %}

  </div>

</div>
{% endblock content %}

{% block extra_body_js %}
{% endblock extra_body_js %}

moms/private/templates/private/charts.html
{% load static %}
{% extends "private/blank_page.html" %}

{% block extra_head_css %}
<!-- Morris Charts CSS -->
<link href="{% static 'css/plugins/morris.css' %}" rel="stylesheet">
{% endblock extra_head_css %}


{% block page %}
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Charts
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
      </li>
      <li class="active">
        <i class="fa fa-bar-chart-o"></i> Charts
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->

<!-- Flot Charts -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Flot Charts</h2>
    <p class="lead">Flot is a pure JavaScript plotting library for jQuery, with a focus on simple usage, attractive looks and interactive features. For full usage instructions and documentation for Flot Charts, visit <a href="http://www.flotcharts.org/">http://www.flotcharts.org/</a>.</p>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Line Graph Example with Tooltips</h3>
      </div>
      <div class="panel-body">
        <div class="flot-chart">
          <div class="flot-chart-content" id="flot-line-chart"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-green">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Pie Chart Example with Tooltips</h3>
      </div>
      <div class="panel-body">
        <div class="flot-chart">
          <div class="flot-chart-content" id="flot-pie-chart"></div>
        </div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Multiple Axes Line Graph Example with Tooltips and Raw Data</h3>
      </div>
      <div class="panel-body">
        <div class="flot-chart">
          <div class="flot-chart-content" id="flot-multiple-axes-chart"></div>
        </div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Moving Line Chart</h3>
      </div>
      <div class="panel-body">
        <div class="flot-chart">
          <div class="flot-chart-content" id="flot-moving-line-chart"></div>
        </div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Bar Graph with Tooltips</h3>
      </div>
      <div class="panel-body">
        <div class="flot-chart">
          <div class="flot-chart-content" id="flot-bar-chart"></div>
        </div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<!-- Morris Charts -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Morris Charts</h2>
    <p class="lead">Morris.js is a very simple API for drawing line, bar, area and donut charts. For full usage instructions and documentation for Morris.js charts, visit <a href="http://morrisjs.github.io/morris.js/">http://morrisjs.github.io/morris.js/</a>.</p>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-green">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Area Line Graph Example with Tooltips</h3>
      </div>
      <div class="panel-body">
        <div id="morris-area-chart"></div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Donut Chart Example</h3>
      </div>
      <div class="panel-body">
        <div id="morris-donut-chart"></div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-red">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Line Graph Example with Tooltips</h3>
      </div>
      <div class="panel-body">
        <div id="morris-line-chart"></div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i> Bar Graph Example</h3>
      </div>
      <div class="panel-body">
        <div id="morris-bar-chart"></div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->
{% endblock page %}

{% block extra_body_js %}
<!-- Morris Charts JavaScript -->
<script src="{% static 'js/plugins/morris/raphael.min.js' %}"></script>
<script src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
<script src="{% static 'js/plugins/morris/morris-data.js' %}"></script>

<!-- Flot Charts JavaScript -->
<script src="js/plugins/flot/jquery.flot.js"></script>
<script src="js/plugins/flot/jquery.flot.tooltip.min.js"></script>
<script src="js/plugins/flot/jquery.flot.resize.js"></script>
<script src="js/plugins/flot/jquery.flot.pie.js"></script>
<script src="js/plugins/flot/flot-data.js"></script>
{% endblock extra_body_js %}

moms/private/templates/private/dashboard.html
{% load static %}
{% extends "private/blank_page.html" %}

{% block extra_head_css %}
<!-- Morris Charts CSS -->
<link href="{% static 'css/plugins/morris.css' %}" rel="stylesheet">
{% endblock extra_head_css %}

{% block page %}
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Dashboard <small>Statistics Overview</small>
    </h1>
    <ol class="breadcrumb">
      <li class="active">
        <i class="fa fa-dashboard"></i> Dashboard
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="alert alert-info alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="fa fa-info-circle"></i>  <strong>Like SB Admin?</strong> Try out <a href="http://startbootstrap.com/template-overviews/sb-admin-2" class="alert-link">SB Admin 2</a> for additional features!
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-comments fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">26</div>
            <div>New Comments!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">12</div>
            <div>New Tasks!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-shopping-cart fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">124</div>
            <div>New Orders!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-support fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">13</div>
            <div>Support Tickets!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Area Chart</h3>
      </div>
      <div class="panel-body">
        <div id="morris-area-chart"></div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Donut Chart</h3>
      </div>
      <div class="panel-body">
        <div id="morris-donut-chart"></div>
        <div class="text-right">
          <a href="#">View Details <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Tasks Panel</h3>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <a href="#" class="list-group-item">
            <span class="badge">just now</span>
            <i class="fa fa-fw fa-calendar"></i> Calendar updated
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">4 minutes ago</span>
            <i class="fa fa-fw fa-comment"></i> Commented on a post
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">23 minutes ago</span>
            <i class="fa fa-fw fa-truck"></i> Order 392 shipped
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">46 minutes ago</span>
            <i class="fa fa-fw fa-money"></i> Invoice 653 has been paid
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">1 hour ago</span>
            <i class="fa fa-fw fa-user"></i> A new user has been added
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">2 hours ago</span>
            <i class="fa fa-fw fa-check"></i> Completed task: "pick up dry cleaning"
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">yesterday</span>
            <i class="fa fa-fw fa-globe"></i> Saved the world
          </a>
          <a href="#" class="list-group-item">
            <span class="badge">two days ago</span>
            <i class="fa fa-fw fa-check"></i> Completed task: "fix error on sales page"
          </a>
        </div>
        <div class="text-right">
          <a href="#">View All Activity <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Transactions Panel</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped">
            <thead>
              <tr>
                <th>Order #</th>
                <th>Order Date</th>
                <th>Order Time</th>
                <th>Amount (USD)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>3326</td>
                <td>10/21/2013</td>
                <td>3:29 PM</td>
                <td>$321.33</td>
              </tr>
              <tr>
                <td>3325</td>
                <td>10/21/2013</td>
                <td>3:20 PM</td>
                <td>$234.34</td>
              </tr>
              <tr>
                <td>3324</td>
                <td>10/21/2013</td>
                <td>3:03 PM</td>
                <td>$724.17</td>
              </tr>
              <tr>
                <td>3323</td>
                <td>10/21/2013</td>
                <td>3:00 PM</td>
                <td>$23.71</td>
              </tr>
              <tr>
                <td>3322</td>
                <td>10/21/2013</td>
                <td>2:49 PM</td>
                <td>$8345.23</td>
              </tr>
              <tr>
                <td>3321</td>
                <td>10/21/2013</td>
                <td>2:23 PM</td>
                <td>$245.12</td>
              </tr>
              <tr>
                <td>3320</td>
                <td>10/21/2013</td>
                <td>2:15 PM</td>
                <td>$5663.54</td>
              </tr>
              <tr>
                <td>3319</td>
                <td>10/21/2013</td>
                <td>2:13 PM</td>
                <td>$943.45</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="text-right">
          <a href="#">View All Transactions <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->
{% endblock page %}

{% block extra_body_js %}
<!-- Morris Charts JavaScript -->
<script src="{% static 'js/plugins/morris/raphael.min.js' %}"></script>
<script src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
<script src="{% static 'js/plugins/morris/morris-data.js' %}"></script>
{% endblock extra_body_js %}

moms/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mobile Oriented Management System</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    {% block extra_head_css %}
    {% endblock extra_head_css %}
    
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    
    <!-- No support for IE8 -->
</head>

<body>

    <div id="wrapper">

      {% block navbar %}
      {% endblock navbar %}
      {% block content %}
      {% endblock content %}
      
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block extra_body_js %}
    {% endblock extra_body_js %}
    
</body>

</html>